In [2]:
import math
from math import factorial
from math import exp
import scipy
from random import random
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.distributions as tdist


In [4]:
import os
import sys
import inspect
    
# insert root dir into sys
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
root_dir = os.path.dirname(currentdir)
# print(root_dir)

if root_dir not in sys.path:
     sys.path.insert(0, root_dir)
   

In [5]:
math.factorial(0)

1

In [6]:
def c(n, k):
    if k > n:
        return(0)
    return(int(math.factorial(n)/(math.factorial(n-k)
               * math.factorial(k))))
def binomial(n, k, p):
    if p > 1:
        raise(Exception("p>1"))
    return(c(n, k)*p**k*(1-p)**(n-k))

In [7]:
binomial(3,0, 0.5)

0.125

##### Direct (definition) method
Sampling with use of <br>
$\sum_{x_{i}\leq x} x_{i} \leq u < \sum_{x_{i}>x} x_{i}$<br>
where `u` from `Uniform(0, 1)`:

In [8]:
from sim0 import Dist, Dist0

$f_{X}(x) = \frac{1}{b-a}$<br>
$F_{X}(x) = \frac{x-a}{b-a}$

In [19]:
class UniformAB0(Dist0):
    def __init__(self, a, b, dx=0.01):
        Dist0.__init__(self, dx=dx)
       
        self.a = a
        self.b = b
        
    def f(self, x):
        a = self.a
        b = self.b
        if a <= x <= b:
            return(1/(b-a))
        else:
            return(0)

In [118]:
# uniform_ab0 = UniformAB0(3, 7, dx=1)
uniform_ab0 = UniformAB0(3, 7, dx=0.001)
uniform_ab0.F(3.01)
uniform_ab0.sample_n(1, dbg=True)
# uniform_ab0.dx

0.7174861012218045 0.7174999999999487 5.870000000000295


array([5.87])

In [119]:
print(uniform_ab0.F(5.870000000000295))
print(sum([uniform_ab0.f(i) for i in range(7)]))
print([uniform_ab0.f(i) for i in range(8)])
uniform_ab0.f(5)

0.7172499999999488
1.0
[0, 0, 0, 0.25, 0.25, 0.25, 0.25, 0.25]


0.25

In [108]:
%matplotlib
plt.plot(list(map(uniform_ab0.F, np.linspace(3, 7, 100))))

Using matplotlib backend: Qt5Agg


In [120]:
%matplotlib
xs = uniform_ab0.sample_n(700)

plt.hist(xs, 7, # density=True, 
        stacked=True)



Using matplotlib backend: Qt5Agg


(array([ 90.,  92., 110., 116., 109.,  81., 102.]),
 array([3.019     , 3.58614286, 4.15328571, 4.72042857, 5.28757143,
        5.85471429, 6.42185714, 6.989     ]),
 <a list of 7 Patch objects>)

##### Inverse transform alg
[1, p 39] Sampling with use of <br>
$X = F_{X}^{-1}(U)$ <br>
where `U = Uniform(0, 1)`:

In [4]:
from sim0 import Dist1

In [5]:
class UniformAB1(Dist1):
    def __init__(self, a, b, dx=0.01):
        self.a = a
        self.b = b
        
    def inv_F(self, y):
        a = self.a
        b = self.b
        return(a + (b-a)*y)

In [111]:
uniform_ab1 = UniformAB1(3, 7)
uniform_ab1.sample_n(3)

array([4.36731585, 6.95716109, 3.21874554])

In [112]:
# check with direct method:
uniform_ab0.F(6.71723186)

0.9292499999999254

In [59]:
%matplotlib
xs = uniform_ab1.sample_n(700)

plt.hist(xs, 7, # density=True, 
        stacked=True)


Using matplotlib backend: Qt5Agg


(array([100.,  92., 105.,  97., 104., 102., 100.]),
 array([3.00164451, 3.57267095, 4.14369739, 4.71472384, 5.28575028,
        5.85677672, 6.42780316, 6.9988296 ]),
 <a list of 7 Patch objects>)

$f_{X}(x) = 2 x$ where $x \in [0, 1]$<br>
$F_{X}(x) = \int 2 x = x^{2}$

In [145]:
class Square0(Dist0):
    
    def f(self, x):
        if 0 <= x <= 1:
            return(7*x**6)
        else:
            return(0)

In [149]:
sdist0 = Square0(dx=0.0001)
sdist0.F(0)
sdist0.sample_n(30)

array([0.586 , 0.7412, 0.7356, 0.9404, 0.8094, 0.6693, 0.9806, 0.9454,
       0.9068, 0.9772, 0.8935, 0.947 , 0.5723, 0.8061, 0.8214, 0.726 ,
       0.9199, 0.7249, 0.8754, 0.7256, 0.9619, 0.988 , 0.7694, 0.7481,
       0.8655, 0.6987, 0.7677, 0.9227, 0.9504, 0.8151])

In [150]:
%matplotlib
xs = sdist0.sample_n(300)

plt.hist(xs, 7, # density=True, 
        stacked=True)

Using matplotlib backend: Qt5Agg


(array([  3.,   4.,  11.,  25.,  43.,  74., 140.]),
 array([0.4555    , 0.53322857, 0.61095714, 0.68868571, 0.76641429,
        0.84414286, 0.92187143, 0.9996    ]),
 <a list of 7 Patch objects>)

In [151]:
class Square1(Dist1):
        
    def inv_F(self, y):
        return(math.sqrt(math.pow(y, 1/7)))

In [152]:
sdist1 = Square1()
sdist1.sample_n(3)

array([0.89658409, 0.84373091, 0.84788881])

In [153]:
%matplotlib
xs = sdist1.sample_n(1700)

plt.hist(xs, 7, # density=True, 
        stacked=True)

Using matplotlib backend: Qt5Agg


(array([  5.,  12.,  31.,  79., 187., 435., 951.]),
 array([0.60829778, 0.66424759, 0.7201974 , 0.77614721, 0.83209702,
        0.88804682, 0.94399663, 0.99994644]),
 <a list of 7 Patch objects>)

In [62]:
class Binomial(Dist):
    def __init__(self, n, p):
        Dist.__init__(self)
        self.n = n
        self.p = p
         
    def f(self, m):
        return(binomial(self.n, m, self.p))
    
     
    def sample1(self):
        run = lambda: 1 if random() >= self.p else 0
        return(sum([run() for k in range(self.n)]))

    def sample1_n(self, n):
        return(np.array([self.sample1() for k in range(n)]))

In [63]:
binomial(3, 2, 0.5)

0.375

In [66]:
bdist = Binomial(3, 0.5)
bdist.F(2)
bdist.sample_n(100)

array([2, 2, 2, 1, 2, 3, 0, 1, 2, 1, 3, 2, 2, 2, 2, 1, 3, 2, 2, 3, 1, 2,
       2, 3, 0, 2, 2, 3, 1, 1, 2, 2, 1, 2, 3, 2, 3, 1, 0, 0, 1, 1, 2, 3,
       2, 0, 3, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 0, 1, 2, 0, 1, 1,
       0, 0, 2, 1, 1, 1, 0, 1, 2, 3, 2, 0, 2, 2, 2, 3, 1, 0, 3, 1, 1, 2,
       2, 2, 3, 2, 0, 1, 2, 1, 0, 2, 1, 2])

In [377]:
print(bdist.F(3))
print(sum([bdist.f(i) for i in range(4)]))
print([bdist.f(i) for i in range(4)])


1.0
1.0
[0.125, 0.375, 0.375, 0.125]


In [383]:
%matplotlib
xs = bdist.sample_n(700)

plt.hist(xs, 7, # density=True, 
        stacked=True)


Using matplotlib backend: Qt5Agg
0.9490723693677193 1.0 3
0.8363026407535477 0.875 2
0.6070353884475855 0.875 2
0.08995274771917405 0.125 0
0.14388831555942694 0.5 1
0.7170115870584015 0.875 2
0.6090341869651563 0.875 2
0.6124123215891999 0.875 2
0.6865316881186089 0.875 2
0.9812872569001775 1.0 3
0.07567244802167761 0.125 0
0.9586332590753087 1.0 3
0.8724857358020986 0.875 2
0.8363162811694937 0.875 2
0.39354132122779206 0.5 1
0.711448744697519 0.875 2
0.23275716733107255 0.5 1
0.20377516043573363 0.5 1
0.5971834221157556 0.875 2
0.7736796201949763 0.875 2
0.12437776833537251 0.125 0
0.8906210639564317 1.0 3
0.47077317191984824 0.5 1
0.44853238458785116 0.5 1
0.00048467164522347783 0.125 0
0.8024442747925119 0.875 2
0.2828538356468874 0.5 1
0.2835456500775998 0.5 1
0.04378679162604726 0.125 0
0.09619694359794295 0.125 0
0.8173890361120032 0.875 2
0.04495371834925277 0.125 0
0.868300425936259 0.875 2
0.3491033244159434 0.5 1
0.23333586628270186 0.5 1
0.5510566182921048 0.875 2
0.767923

0.35373348742756827 0.5 1
0.3409538757090451 0.5 1
0.41665509895218134 0.5 1
0.5700967896002794 0.875 2
0.13502775542174938 0.5 1
0.39498551250389646 0.5 1
0.6078873503984157 0.875 2
0.31064991498101546 0.5 1
0.21340450681041567 0.5 1
0.38523078291683643 0.5 1
0.04460316346400761 0.125 0
0.271710381977852 0.5 1
0.1356134269003545 0.5 1
0.531212038254203 0.875 2
0.405902525780899 0.5 1
0.7993048739362419 0.875 2
0.08162832251432339 0.125 0
0.011761256995082237 0.125 0
0.3345154747078337 0.5 1
0.7439019753080011 0.875 2
0.8912467091039799 1.0 3
0.8596138732586042 0.875 2
0.9755605742353307 1.0 3
0.7419828724237677 0.875 2
0.7306611364323552 0.875 2
0.6633377508933124 0.875 2
0.55835383019423 0.875 2
0.7174495372662315 0.875 2
0.5862763242085447 0.875 2
0.42151819298539284 0.5 1
0.9093714037509709 1.0 3
0.430513427651133 0.5 1
0.3064026074944072 0.5 1
0.08285165093896052 0.125 0
0.2911467130295585 0.5 1
0.314110765970517 0.5 1
0.76695217504215 0.875 2
0.784303141531126 0.875 2
0.172793435

(array([ 90.,   0., 279.,   0., 256.,   0.,  75.]),
 array([0.        , 0.42857143, 0.85714286, 1.28571429, 1.71428571,
        2.14285714, 2.57142857, 3.        ]),
 <a list of 7 Patch objects>)

In [18]:
%matplotlib
plt.plot([bdist.f(m) for m in range(7)])

Using matplotlib backend: Qt5Agg


In [181]:
class Poisson(Dist):
    def __init__(self, l):
        Dist.__init__(self)
        self.l = l
            
    def f(self, k):
        return((self.l**k/factorial(k))*exp(-self.l))
    

In [182]:
pdist = Poisson(10)

In [183]:
pdist.F(10)

0.5830397501929856

In [184]:
pdist.f(30)

1.7115717355367894e-07

In [185]:
%matplotlib
xs = pdist.sample_n(700)

plt.hist(xs, 30, # density=True, 
        stacked=True)

Using matplotlib backend: Qt5Agg


(array([ 1.,  2.,  3.,  0., 12., 27., 47.,  0., 63., 74., 87.,  0., 79.,
        80.,  0., 75., 58., 37.,  0., 23.,  9., 12.,  0.,  7.,  3.,  0.,
         0.,  0.,  0.,  1.]),
 array([ 2.        ,  2.73333333,  3.46666667,  4.2       ,  4.93333333,
         5.66666667,  6.4       ,  7.13333333,  7.86666667,  8.6       ,
         9.33333333, 10.06666667, 10.8       , 11.53333333, 12.26666667,
        13.        , 13.73333333, 14.46666667, 15.2       , 15.93333333,
        16.66666667, 17.4       , 18.13333333, 18.86666667, 19.6       ,
        20.33333333, 21.06666667, 21.8       , 22.53333333, 23.26666667,
        24.        ]),
 <a list of 30 Patch objects>)

In [42]:
# same with torch
tpdist = tdist.Poisson(10*torch.ones(700))

In [43]:
%matplotlib
plt.hist(tpdist.sample(), 30, # density=True, 
        stacked=True)

Using matplotlib backend: Qt5Agg


(array([ 1.,  6., 12.,  0., 29., 40.,  0., 57., 88.,  0., 84., 92., 84.,
         0., 62., 55.,  0., 37., 31.,  0., 17.,  2.,  0.,  0.,  2.,  0.,
         0.,  0.,  0.,  1.]),
 array([ 2. ,  2.7,  3.4,  4.1,  4.8,  5.5,  6.2,  6.9,  7.6,  8.3,  9. ,
         9.7, 10.4, 11.1, 11.8, 12.5, 13.2, 13.9, 14.6, 15.3, 16. , 16.7,
        17.4, 18.1, 18.8, 19.5, 20.2, 20.9, 21.6, 22.3, 23. ],
       dtype=float32),
 <a list of 30 Patch objects>)

### Refs
1) Simulation and the Monte Carlo Method by Reuven Y. Rubinstein